name: CI
on: 
  push:
    branches:
      - otax/production
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --include=dev --unsafe-perm
    - run: npm i better-npm-run && npx better-npm-run test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 8.x
        cache: 'npm'
    - run: npm install --include=dev --unsafe-perm
    - run: npm run lint