name: CI
on: 
  push:
    branches:
      - otax/production
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 8.x
        cache: 'npm'
    - run: npm install --include=dev
    - run: npm run lint